---
title: "Languages"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r, include=FALSE, echo=FALSE}
library(tidyverse)
library(lingtypology)
library(lingglosses)
df <- read.csv("data.csv", na.strings=c("","NA"))
df %>%
  filter(df$truth_word == "yes") %>%
  select(-id_number, -really_pred_excluded) %>%
  select(-contains("_comment"))-> df

#renumerate indexes after filtering for truth-words (otherwise the loop below doesn't work)
df <- tibble::rowid_to_column(df, "id_number") 

```





```{r, echo=FALSE, results='asis'}
for (f in unique(df$language_name)) {
  cat('\n\n## ', f, '\n',
      sep="")
  
  
  for (i in df$id_number[df$language_name == f]) {
    word <- as.character(df$word[df$id_number == i])
    translation <- as.character(df$translation[df$id_number == i])
    
    cat('\n \n### ', word, ' \'', translation, '\'',
      sep="")
    
    for (c in 13:ncol(df)) { 
      if (!is.na(df[i, c])) {
        ex <- unlist(strsplit(df[i, c], split = "\n"))
        cat('\n \n#### ', colnames(df)[c], '\n \n (@)', ex[1],' \n  ', ex[2] )
      }
      
    }
  }
  
  cat('\n \n --- \n \n')
}

```



