---
title: "Summary and visualizations"
---


<style type="text/css">
.main-container {
    max-width: 1170px;
    
}
</style>



```{r, include=FALSE, echo=FALSE}
library(tidyverse)
library(lingtypology)
library(readr)
library(DT)

df_orig <- read.csv("data.csv", na.strings=c("","NA"))
df_orig %>%
  filter(truth_word == "yes") %>%
  select(-"id_number", -"researcher", -"iso", -"family", -"consultant", -"questionnaire_language", -"elicitation_method", -"truth_word", -"word_group", -"really_pred_excluded") %>%
  select(-contains("_comment"))-> df


df %>%
  mutate(across(.cols = c(4:ncol(df)), .fns = function(x) ifelse(!is.na(x), "+", ""))) -> df

```


## Questionnaire results {.tabset}

### All functions

```{r echo = FALSE, results = 'asis', message=FALSE, warning=FALSE}
datatable(
  data = df,
  filter = "top",
  extensions = 'FixedColumns',
  options = list(fixedColumns = list(leftColumns = 4), scrollX = TRUE, dom = 'Bfrtip',
                 columnDefs = list(list(className = 'dt-center', targets = "_all")))
  
)
```

---


### Generalized extended functions


```{r, include=FALSE, echo=FALSE}
df %>%
  mutate(int = ifelse(int_adj == "+" | int_npred == "+" | int_pred == "+",
                        "+", "")) %>%
  mutate(conc = ifelse(conc_pred1 == "+" | conc_pred2 == "+" | conc_adj == "+" | conc_adv == "+",
                        "+", "")) %>%
  select("language_name", "word", "translation", "int", "tag", "affirm", "conc", "subj") -> df_gen
df_gen
```

```{r echo = FALSE, results = 'asis', message=FALSE, warning=FALSE}
datatable(
  data = df_gen,
  filter = "top",
  extensions = 'FixedColumns',
  options = list(scrollX = TRUE, dom = 'Bfrtip',
                 columnDefs = list(list(className = 'dt-center', targets = "_all")))
  
)
```

---

## Maps 

### All functions {.tabset}

```{r, include=FALSE, echo=FALSE}
df %>%
  group_by(language_name) %>%
  summarize(across(truth_pred:subj, ~ ifelse(("+" %in% .x), "attested", "not attested"))) -> df_per_lng

#restore iso-codes
df_orig %>%
  select("language_name", "iso") %>%
  unique() -> iso_codes
df_iso <- merge (df_per_lng, iso_codes, by = "language_name")
```


#### right

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$right,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "\'right\'"
            )
```

#### genuine

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$genuine,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "\'real (genuine, not fake)\'"
            )
```

#### real

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$real,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "\'real (not imagined)\'"
            )
```


#### int_adj

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$int_adj,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "intensification (of adjective)"
            )
```


#### int_npred

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$int_npred,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "intensification (of non-verbal predicate)"
            )
```

#### int_pred

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$int_pred,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "intensification (of verbal predicate)"
            )
```


#### CL

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$CL,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "counter-loosener (\'proper\')"
            )
```

#### select

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$select,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "selective (\'the only real\')"
            )
```

#### tag

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$tag,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "tag-question"
            )
```

#### affirm

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$affirm,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "affirmation"
            )
```

#### conc_pred1

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$conc_pred1,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "concessive (Q, but the truth is that P)"
            )
```

#### conc_pred2

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$conc_pred2,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "concessive (It is true that P, but Q)"
            )
```

#### conc_adj

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$conc_adj,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "concessive (+ adjective)"
            )
```

#### conc_adv

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$conc_adv,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "concessive (+ adverbial)"
            )
```

#### subj

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_iso$iso),
            features = df_iso$subj,
            label = df_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "subjectification"
            )
```

---

### Generalized extended functions {.tabset}

```{r, include=FALSE, echo=FALSE}
df_gen %>%
  group_by(language_name) %>%
  summarize(across(int:subj, ~ ifelse(("+" %in% .x), "attested", "not attested"))) -> df_per_lng

#restore iso-codes
df_orig %>%
  select("language_name", "iso") %>%
  unique() -> iso_codes
df_gen_iso <- merge (df_per_lng, iso_codes, by = "language_name")
```




```{r, echo=FALSE, include=FALSE}
#for neighbbor-net
df %>%
  group_by(language_name) %>%
  summarize(across(right:subj, ~ ifelse(("+" %in% .x), "1", "0"))) -> df
write.csv(df, "df.csv")
```



#### Intensification

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_gen_iso$iso),
            features = df_gen_iso$int,
            label = df_gen_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "Intensification"
            )
```


#### Tag-question

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_gen_iso$iso),
            features = df_gen_iso$tag,
            label = df_gen_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "Tag-question"
            )
```

#### Affirmation

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_gen_iso$iso),
            features = df_gen_iso$affirm,
            label = df_gen_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "Affirmation"
            )
```


#### Concessive

```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_gen_iso$iso),
            features = df_gen_iso$conc,
            label = df_gen_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "Concessive"
            )
```

#### Subjectification


```{r, echo=FALSE, out.width = '100%'}
  
map.feature(languages = lang.iso(df_gen_iso$iso),
            features = df_gen_iso$subj,
            label = df_gen_iso$iso, label.hide = FALSE, label.fsize = 10,
            tile = "Esri.WorldPhysical",
            color = c("#f46d43", "#404040"),
            width = 6,
            title = "Subjectification"
            )
```




